### ISSUE TITLE
Missing data potential bug?

### ISSUE THREAD

**Issue by dsamojlenko** [cds-snc/c19-benefits-node#213] opened 2020-04-13 22:38 UTC
Posting as-submitted, for investigation. Not sure how this state was reached.

> When I get to the last page, (Check back in a few weeks), I’m told “You missed a couple questions at the beginning. Start over<https://cv19benefits-appservice.azurewebsites.net/clear> to get your full results.”  But I’m not told which ones I missed.  I should be told.  Ideally I should be given a link to go back to those pages.  I wonder if this is when I was checking clicking “Next” without selecting a radio button.  I eventually did select a radio button each time in order to make it to the next page.  So, there may be a back-end bug here.

> Update:  I just started over, going through the whole process, always choosing a definitive answer (avoiding any “I’m not sure” style of answers), and I still get that error message.

**Comment by katedee** [comment] 2020-04-22 13:35
Can't reproduce this, closing for now

**Closed by katedee** 2020-04-22 13:35 UTC
